name: draft_home
description: "A new Flutter project for web pages."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  webview_flutter: ^4.2.2
  video_player: ^2.6.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  provider: 6.1.2
  flutter_gen: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/l10n/app_en.arb
    - assets/l10n/app_ko.arb
    - assets/draft/logo_draft_transparentBG.png
    - assets/draft/crumpled_paper_1405.jpg
    - assets/draft/logo_symbol_draft.png
    - assets/dusty/logo_dustydraft.png
    - assets/dusty/dusty-agent-white.png
    - assets/dusty/logo_symbol_draft_grey.png
    - assets/dusty/DRAFT_dustydraft_service-description_24.pdf
    - assets/dusty/brown-background-water-reflection-texture.jpg
    - assets/exotic/evotic.png
    - assets/exotic/exotic-48x48.png
    - assets/exotic/exoticordinary_background.jpg
    - assets/exotic/logo_exoticordinary.png
    - assets/boutique/door_image.jpg
    - assets/boutique/logo_the_boutique.png
    - assets/boutique/exotic-yellow.png
    - assets/boutique/evotic-48x48.png
    - assets/ordinary/symbol_about_us.png
    - assets/ordinary/background_1.png
    - assets/ordinary/AdobeStock_712861746.jpeg
    - assets/ordinary/about_us.png
    - assets/ordinary/OL_setup_detail_page.png
    - assets/videos/7624037-uhd_2160_3840_30fps.mp4
    - assets/AdobeStock_228406900.jpeg
    - assets/instagram_icon.png
    - lib/contents/PrivacyPolicy.md
    - lib/contents/TermsOfService.md

  fonts:
    - family: DraftFont
      fonts:
        - asset: assets/fonts/draft/IBMPlexSerif-Regular.ttf
        - asset: assets/fonts/draft/Barlow-Regular.ttf
        - asset: assets/fonts/draft/PretendardVariable.ttf      
    - family: DustyFont
      fonts:
        - asset: assets/fonts/dusty/BarlowSemiCondensed-Regular.ttf
        - asset: assets/fonts/dusty/RalewayDots-Regular.ttf
        - asset: assets/fonts/dusty/PretendardVariable.ttf
    - family: ExoticFont
      fonts:
        - asset: assets/fonts/exotic/DancingScript-Regular.ttf
        - asset: assets/fonts/exotic/Lora-Regular.ttf
        - asset: assets/fonts/exotic/PretendardVariable.ttf
    - family: BoutiqueFont
      fonts:
        - asset: assets/fonts/boutique/CormorantGaramond-Regular.ttf
        - asset: assets/fonts/boutique/Poppins-Regular.ttf
        - asset: assets/fonts/boutique/PretendardVariable.ttf
    - family: OrdinaryFont
      fonts:
        - asset: assets/fonts/ordinary/Montserrat-Regular.ttf
        - asset: assets/fonts/ordinary/Lato-Regular.ttf
        - asset: assets/fonts/ordinary/PretendardVariable.ttf
  
flutter_localizations:
  delegates:
    - GlobalMaterialLocalizations.delegate
    - GlobalWidgetsLocalizations.delegate
    - GlobalCupertinoLocalizations.delegate
  supportedLocales:
    - en
    - ko